apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
  labels:
    app: knote
    team: team-a
    env: dev
    department: dep-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
        team: team-a
        env: dev
        department: dep-1
    spec:
      containers:
      - name: app
        image: localhost/knote
        imagePullPolicy: IfNotPresent
        # imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongodb
                key: database-name
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: database-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: database-password
          - name: MONGO_URL
            value: mongodb
        resources:
          requests:
            memory: 512Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
